Repository clubgamma/club-gamma-frontend, pull requests merged in 2024-10, with the labels that each got.

#3 fix: base
  package-lock.json
  package.json
  vite.config.js
Labels: bug

#10 fix: register button on home page, page content hidden under navbar
  package-lock.json
  src/Pages/Home.jsx
  src/Pages/LeaderBoard.jsx
  src/components/Hero.jsx
  src/components/Navbar.jsx
  src/components/Q&A.jsx
  src/components/Stat.jsx
Labels: bug, hacktoberfest-accepted

#19 fix: Add GitHub Profile Picture And Username in Leaderboard Page
  src/Pages/LeaderBoard.jsx
Labels: level 1, hacktoberfest-accepted

#20 fix: Reduce Hover Reflection Time in 'Our Projects' Section
  src/components/Projects.jsx
Labels: bug, hacktoberfest-accepted

#22 Simplified contributor fetch function
  src/Pages/LeaderBoard.jsx
Labels: level 2, hacktoberfest-accepted

#24 Fixed: Hover Functionality not Working on Mobile Devices.
  src/components/Projects.jsx
Labels: bug, hacktoberfest-accepted

#25 Stat component now fetches data dynamically
  src/Global.js
  src/components/Stat.jsx
Labels: level 1, hacktoberfest-accepted

#31 Made the Readme.md file cooler and better
  README.md
Labels: documentation, hacktoberfest-accepted

#33 Add yearwise Event
  package-lock.json
  package.json
  src/App.jsx
  src/Pages/Events.jsx
  src/assets/AI.jpeg
  src/components/EventCard.jsx
  src/components/Navbar.jsx
  src/components/ui/navigation-menu.jsx
  src/components/ui/separator.jsx
Labels: level 3, hacktoberfest-accepted

#36 Add Team Section
  src/App.jsx
  src/Pages/Team.jsx
  src/components/Navbar.jsx
  src/components/TeamCard.jsx
Labels: level 3, hacktoberfest-accepted

#37 feat: contact us social icons responsiveness
  src/components/ContactUs.jsx
Labels: bug, hacktoberfest-accepted

#39 Fixed scrolling disabled after returning from Event Details
  src/Pages/Home.jsx
  src/components/EventCard.jsx
Labels: bug, hacktoberfest-accepted

#42 Display Error Message When Profile Does Not Exist in /profile/:username
  bun.lockb
  src/Pages/Profile.jsx
Labels: bug, hacktoberfest-accepted

#45 Point-system page
  package.json
  src/App.jsx
  src/Pages/LeaderBoard.jsx
  src/Pages/PointSystem.jsx
  src/components/ui/table.jsx
  src/components/ui/tooltip.jsx
  src/index.css
Labels: level 3, hacktoberfest-accepted

#41 open user profile from leaderboard
  src/Pages/LeaderBoard.jsx
Labels: level 1, hacktoberfest-accepted

#54 Added smooth scrolling
  package.json
  src/App.jsx
Labels: level 1, hacktoberfest-accepted

#62 updated Project contributer section
  src/App.jsx
  src/Pages/Contributors.jsx
  src/components/Projects.jsx
Labels: level 3, hacktoberfest-accepted

#67 SEO and Analytics
  package.json
  public/og_image.png
  public/robots.txt
  public/sitemap.xml
  src/App.jsx
  src/Pages/Contributors.jsx
  src/Pages/Events.jsx
  src/Pages/Home.jsx
  src/Pages/LeaderBoard.jsx
  src/Pages/PointSystem.jsx
  src/Pages/Team.jsx
  src/components/SEO.jsx
  src/components/SEOLayout.jsx
Labels: level 3, hacktoberfest-accepted

#68 Conribution activity in heatmap
  bun.lockb
  src/Pages/Profile.jsx
  src/components/Navbar.jsx
  src/components/Projects.jsx
Labels: level 3, hacktoberfest-accepted

#70 Added 404 Page
  src/App.jsx
  src/assets/404-animation.json
  src/components/NotFound.jsx
Labels: level 3, hacktoberfest-accepted

#71 Added Error Boundary
  package.json
  src/assets/error.json
  src/components/ErrorFallback.jsx
  src/main.jsx
Labels: level 3, hacktoberfest-accepted

#72 Open GitHub Page When PR Card is Clicked
  src/Pages/Profile.jsx
Labels: level 1, hacktoberfest-accepted

#74 Added Margin in stats
  src/components/Stat.jsx
Labels: bug, hacktoberfest-accepted

#77 Add UI for syncing PRs
  src/Pages/Profile.jsx
  src/components/SyncPRs.jsx
Labels: level 2, hacktoberfest-accepted

#79 Filtering and Categories in Projects
  src/components/Projects.jsx
Labels: level 2, hacktoberfest-accepted

#80 Improved User Button/Dropdown
  src/components/Navbar.jsx
  src/components/Projects.jsx
Labels: level 1, hacktoberfest-accepted

#82 Side bar blur
  src/components/Navbar.jsx
Labels: bug, hacktoberfest-accepted

#86 Responsive home page
  src/Pages/Home.jsx
  src/components/EventCard.jsx
  src/components/FAQs.jsx
  src/components/ui/dialog.jsx
Labels: bug, hacktoberfest-accepted

#87 Fixed Dock spacing issue
  src/Pages/Events.jsx
  src/Pages/Home.jsx
  src/Pages/LeaderBoard.jsx
Labels: bug, hacktoberfest-accepted

#90 Change route of project contributors
  src/App.jsx
  src/components/Projects.jsx
Labels: bug, hacktoberfest-accepted

#91 Change footer of hf24 page
  src/Pages/Home.jsx
  src/components/Dock.jsx
  src/components/Footer.jsx
Labels: level 1, hacktoberfest-accepted

#92 Dock spacing issue and route change in contributors
  src/Pages/Contributors.jsx
Labels: bug, hacktoberfest-accepted

#94 Fixed SEO
  public/sitemap.xml
  src/Pages/Hacktober2024.jsx
  src/Pages/Home.jsx
  src/Pages/Profile.jsx
  src/Pages/Team.jsx
  src/components/ProgressLevel.jsx
Labels: bug, hacktoberfest-accepted

#97 About in home page
  package.json
  src/Pages/Home.jsx
  src/components/Navbar.jsx
  src/components/ui/scroll-area.jsx
Labels: level 1, hacktoberfest-accepted

#99 Made Sidebar and Profile Page Responsive
  src/App.jsx
  src/components/Dock.jsx
  src/components/Footer.jsx
  src/components/Navbar.jsx
  src/components/ProgressLevel.jsx
Labels: level 1, hacktoberfest-accepted

#103 Change HFQ&A ui
  src/components/HFQ&A.jsx
Labels: bug, hacktoberfest-accepted

#107 Made PRs Scrollable
  src/Pages/Profile.jsx
Labels: level 1, hacktoberfest-accepted

#117 Made the width of PRs responsive
  src/Pages/Profile.jsx
Labels: bug, hacktoberfest-accepted

#118 not Display Correctly
  src/Pages/PointSystem.jsx
  src/components/HFQ&A.jsx
Labels: bug

#120 Improved Events Section and PRs Section
  src/Pages/Events.jsx
  src/Pages/Profile.jsx
Labels: level 2, hacktoberfest-accepted

#111 implement UI for project wise contribution
  src/Pages/Profile.jsx
  src/components/ProjectContributions.jsx
Labels: level 3, hacktoberfest-accepted

#122 Fixed Dates going to Second line for bigger titles
  src/Pages/Events.jsx
Labels: bug, hacktoberfest-accepted

#124 Improved event modal
  src/components/EventCard.jsx
Labels: level 1, hacktoberfest-accepted

#123 Fixed Profile RecentPRs hight
  src/Pages/Home.jsx
  src/components/Stat.jsx
Labels: bug, hacktoberfest-accepted

#129 Added level in PRs
  package.json
  src/Pages/Profile.jsx
Labels: level 1, hacktoberfest-accepted

#130 Fixed Bug with Level and made it responsive
  src/Pages/Profile.jsx
Labels: bug, hacktoberfest-accepted

#131 Fixed Level Bug and made Project Contributions responsive
  src/Pages/Profile.jsx
  src/components/ProjectContributions.jsx
Labels: bug, hacktoberfest-accepted

#135 Added Filter in PRs and Removed ScrollBar
  src/Pages/Profile.jsx
Labels: level 2, hacktoberfest-accepted

#140 PRs Count Based On Filter
  src/Pages/Profile.jsx
Labels: level 1, hacktoberfest-accepted

#137 Added hover animations in Home Page for better UX
  src/Pages/Home.jsx
Labels: level 2, hacktoberfest-accepted
